name: deploy-azure
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      ACR_NAME: ${{ secrets.ACR_NAME }}
      RG: ${{ secrets.AZURE_RG }}
      APP_NAME: ${{ secrets.AZURE_CONTAINER_APP }}
      SUB_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          client-id: ${{ env.CLIENT_ID }}
          tenant-id: ${{ env.TENANT_ID }}
          subscription-id: ${{ env.SUB_ID }}

      - name: Build and push image
        run: |
          az acr login --name $ACR_NAME
          docker build -t $ACR_NAME.azurecr.io/app:${{ github.sha }} .
          docker push $ACR_NAME.azurecr.io/app:${{ github.sha }}

      - name: Update Container App image
        run: |
          az containerapp update \
            --name $APP_NAME \
            --resource-group $RG \
            --image $ACR_NAME.azurecr.io/app:${{ github.sha }}
