#!/usr/bin/env bash
#
# Environment File Generation Library
#
# Purpose:
#   Generate .env.production file from deployment outputs
#   - Copy base configuration from .env.local
#   - Update Azure-specific variables
#   - Generate secrets (e.g., NextAuth secret)
#   - Add optional service configurations
#
# Uses variables from calling script:
#   - ENV_FILE
#   - SQL_SERVER_FQDN
#   - SQL_DATABASE_NAME
#   - SQL_ADMIN_USER
#   - SQL_ADMIN_PASSWORD
#   - ACR_LOGIN_SERVER
#   - ACR_NAME
#   - KEY_VAULT_NAME
#   - KEY_VAULT_URI
#   - CONTAINER_APP_NAME
#   - CONTAINER_APP_ENV_ID
#   - RESOURCE_GROUP
#   - PREFIX
#   - DEPLOY_STORAGE
#   - DEPLOY_OPENAI
#   - DEPLOY_PUBSUB
#   - DEPLOY_MONITORING
#   - STORAGE_CONN_STRING (if deployed)
#   - OPENAI_ENDPOINT (if deployed)
#   - OPENAI_API_KEY (if deployed)
#   - PUBSUB_CONN_STRING (if deployed)
#   - APP_INSIGHTS_CONN_STRING (if deployed)
#

# ============================================================================
# Environment File Generation Function
# ============================================================================

# Generate .env.production file from deployment outputs
# Exits with error code 1 if .env.local doesn't exist
generate_env_file() {
  print_header "Generating $ENV_FILE"
  
  # ========================================================================
  # Check for .env.local
  # ========================================================================
  
  if [ ! -f ".env.local" ]; then
    print_error ".env.local not found!"
    print_info "Please create .env.local first with your development configuration"
    print_info "This should include Google Auth credentials and other settings"
    exit 1
  fi
  
  # Warn if .env.local contains old Azure resource names
  if grep -q "^ACR_NAME=" ".env.local" 2>/dev/null; then
    local old_acr_name=$(grep "^ACR_NAME=" ".env.local" | cut -d '=' -f2)
    if [ -n "$old_acr_name" ] && [ "$old_acr_name" != "$ACR_NAME" ]; then
      print_warning ".env.local contains old ACR_NAME: $old_acr_name"
      print_info "This will be overwritten with new value: $ACR_NAME"
    fi
  fi
  
  # ========================================================================
  # Copy Base Configuration
  # ========================================================================
  
  print_info "Copying .env.local to $ENV_FILE..."
  cp .env.local "$ENV_FILE"
  print_success "Base configuration copied from .env.local"
  
  # ========================================================================
  # Create Temporary File for Updates
  # ========================================================================
  
  TEMP_FILE="${ENV_FILE}.tmp"
  
  # Add deployment header at the top
  cat > "$TEMP_FILE" << EOF
# ============================================================================
# Azure Production Configuration
# Generated by: scripts/deploy/01_deploy_infrastructure.sh (Phase 1)
# Date: $(date)
# ============================================================================
#
# NOTE: This file was created by copying .env.local and updating deployment-specific variables
# Phase 1 (Foundation) deployment complete
# Container App URL will be added after Phase 2 (05_deploy_container_app.sh)
#

EOF
  
  # Append original .env.local content
  cat .env.local >> "$TEMP_FILE"
  
  # ========================================================================
  # Variable Update Helper Function
  # ========================================================================
  
  # Function to update or add environment variable
  # Parameters:
  #   $1: Variable name
  #   $2: Variable value
  #   $3: Optional comment
  update_or_add_var() {
    local var_name="$1"
    local var_value="$2"
    local comment="${3:-}"  # Optional comment parameter with default empty string
    
    # Escape special characters for sed (/, &, \, newlines)
    local escaped_value=$(printf '%s' "$var_value" | sed 's/[&/\]/\\&/g')
    
    # Check if variable exists in file
    if grep -q "^${var_name}=" "$TEMP_FILE"; then
      # Update existing variable
      sed -i "s|^${var_name}=.*|${var_name}=${escaped_value}|g" "$TEMP_FILE"
    elif grep -q "^#${var_name}=" "$TEMP_FILE"; then
      # Variable exists but is commented out - uncomment and update
      sed -i "s|^#${var_name}=.*|${var_name}=${escaped_value}|g" "$TEMP_FILE"
    else
      # Variable doesn't exist - add it with comment if provided
      if [ -n "$comment" ]; then
        printf "\n# %s\n" "$comment" >> "$TEMP_FILE"
      fi
      printf "%s=%s\n" "$var_name" "$var_value" >> "$TEMP_FILE"
    fi
  }
  
  # ========================================================================
  # Update Node Environment
  # ========================================================================
  
  # CRITICAL: Set NODE_ENV to production for deployment
  # This was set in prepare_production_env() but we need to ensure it stays set
  # after copying .env.local again
  update_or_add_var "NODE_ENV" "production" "Node environment (production for Azure deployment)"
  
  # ========================================================================
  # Update Azure SQL Database Variables
  # ========================================================================
  
  print_info "Updating deployment-specific variables..."
  
  update_or_add_var "MSSQL_SERVER" "$SQL_SERVER_FQDN" "Azure SQL Database (Kysely-compatible format)"
  update_or_add_var "MSSQL_DATABASE" "$SQL_DATABASE_NAME"
  update_or_add_var "MSSQL_USER" "$SQL_ADMIN_USER"
  update_or_add_var "MSSQL_PASSWORD" "$SQL_ADMIN_PASSWORD"
  update_or_add_var "MSSQL_ENCRYPT" "true"
  update_or_add_var "MSSQL_POOL_MIN" "0"
  update_or_add_var "MSSQL_POOL_MAX" "10"
  
  # ========================================================================
  # Generate NextAuth Secret
  # ========================================================================
  
  # Generate NextAuth secret if not already set
  NEXTAUTH_SECRET_VALUE=$(openssl rand -base64 32 2>/dev/null || echo "GENERATE_SECURE_SECRET_$(date +%s)")
  update_or_add_var "NEXTAUTH_SECRET" "$NEXTAUTH_SECRET_VALUE" "NextAuth Configuration"
  
  # NEXTAUTH_URL will be set after Container App deployment (Phase 2)
  update_or_add_var "NEXTAUTH_URL" "" "Will be set in Phase 2 after Container App deployment"
  
  # ========================================================================
  # Update Azure Container Registry Variables
  # ========================================================================
  
  update_or_add_var "ACR_LOGIN_SERVER" "$ACR_LOGIN_SERVER" "Azure Container Registry"
  update_or_add_var "ACR_NAME" "$ACR_NAME"
  
  # ========================================================================
  # Update Azure Key Vault Variables
  # ========================================================================
  
  update_or_add_var "KEY_VAULT_NAME" "$KEY_VAULT_NAME" "Azure Key Vault"
  update_or_add_var "KEY_VAULT_URI" "$KEY_VAULT_URI"
  
  # ========================================================================
  # Update Azure Container App Variables
  # ========================================================================
  
  # Phase 2 will complete these with actual URLs
  update_or_add_var "CONTAINER_APP_NAME" "$CONTAINER_APP_NAME" "Azure Container App (URLs will be set in Phase 2)"
  update_or_add_var "CONTAINER_APP_ENV_ID" "$CONTAINER_APP_ENV_ID"
  update_or_add_var "CONTAINER_APP_FQDN" "" "Will be populated by 05_deploy_container_app.sh"
  update_or_add_var "CONTAINER_APP_URL" "" "Will be populated by 05_deploy_container_app.sh"
  
  # ========================================================================
  # Update Resource Group and Prefix
  # ========================================================================
  
  update_or_add_var "RESOURCE_GROUP" "$RESOURCE_GROUP" "Azure Resource Group"
  update_or_add_var "PREFIX" "$PREFIX" "Resource prefix for Azure resources"
  
  # ========================================================================
  # Add Optional Services
  # ========================================================================
  
  # Azure Storage Account
  if [ "$DEPLOY_STORAGE" = "true" ] && [ -n "$STORAGE_CONN_STRING" ]; then
    update_or_add_var "AZURE_STORAGE_CONNECTION_STRING" "$STORAGE_CONN_STRING" "Azure Storage"
    update_or_add_var "AZURE_STORAGE_CONTAINER" "uploads" "Default storage container"
  fi
  
  # Azure OpenAI
  if [ "$DEPLOY_OPENAI" = "true" ] && [ -n "$OPENAI_ENDPOINT" ]; then
    update_or_add_var "AZURE_OPENAI_ENDPOINT" "$OPENAI_ENDPOINT" "Azure OpenAI"
    update_or_add_var "AZURE_OPENAI_API_KEY" "$OPENAI_API_KEY"
    # Note: AZURE_OPENAI_DEPLOYMENT should be set manually based on your deployment name
  fi
  
  # Azure Web PubSub
  if [ "$DEPLOY_PUBSUB" = "true" ] && [ -n "$PUBSUB_CONN_STRING" ]; then
    update_or_add_var "AZURE_WEB_PUBSUB_CONNECTION_STRING" "$PUBSUB_CONN_STRING" "Azure Web PubSub"
  fi
  
  # Application Insights
  if [ "$DEPLOY_MONITORING" = "true" ] && [ -n "$APP_INSIGHTS_CONN_STRING" ]; then
    update_or_add_var "APPINSIGHTS_CONNECTION_STRING" "$APP_INSIGHTS_CONN_STRING" "Application Insights"
  fi
  
  # ========================================================================
  # Finalize File
  # ========================================================================
  
  # Replace original file with updated version
  mv "$TEMP_FILE" "$ENV_FILE"
  
  print_success "$ENV_FILE generated successfully!"
  print_info "✓ Copied all settings from .env.local (Google Auth, MailerSend, etc.)"
  print_info "✓ Updated Azure infrastructure variables"
  print_info "✓ Stripe variables preserved (configure with 03_configure_stripe.sh if needed)"
  print_warning "Review $ENV_FILE before proceeding to next steps"
}


